[package]
name = "assignment_7_2"
version = "0.1.0"
authors = ["Moghees Bin Zahid"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "mylib"
path = "src/lib.rs"

[dependencies]
